version: 0.2

proxy:
  logs: yes

phases:
  install:
    runtime-versions:
      python: 3.9
  post_build:
    commands:
      - aws s3 cp index s3://ccbd-hw2-frontend/ --recursive
      - aws s3 cp index s3://hw2-frontend-us-east1-cf/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: index
  name: frontend
