version: 0.2

proxy:
  logs: yes

phases:
  install:
    runtime-versions:
      python: 3.9
  post_build:
    commands:
      - aws s3api create-bucket --bucket CCBD-hw2-frontend --region us-east-1
      - aws s3 cp index s3://CCBD-hw2-frontend/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: index
  name: frontend
